using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StartPopUp : MonoBehaviour
{
    public Ship ship;
    public MoveButton leftButton;
    public MoveButton rightButton;
    
    private float shipSpeed;
    private float shipSideSpeed;

    void Start()
    {
        if (GameSettings.Instance.GetLevelCount() == 1)
        {
            shipSpeed = ship.speed;
            shipSideSpeed = ship.sideSpeed;
            ship.speed = 0f;
            ship.sideSpeed = 0f;
        }
        else this.gameObject.SetActive(false);
    }

    void Update()
    {
        if (leftButton.buttonDown || rightButton.buttonDown || Input.GetKey("right") || Input.GetKey("left") )
        {
            ship.speed = shipSpeed;
            ship.sideSpeed = shipSideSpeed;
            this.gameObject.SetActive(false);
        }
    }


}
